[package]
name = "migorengx/lambda-universe"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
networker = "leifstout/networker@0.3.0"
Fusion = "elttob/fusion@0.2.0"
Lydie = "7kayoh/lydie@0.1.0"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"